version: "3.8"
services:
  plexpod:
    build:
      context: https://github.com/jhellerstedt/plex-playlist-podcast.git#v1-refactor-from-jellyfin
      dockerfile: Dockerfile
    image: plexpod:local
    container_name: plexpod
    restart: unless-stopped
    ports:
      - "8585:80"
